### ISSUE TITLE
Foreman Missing partial dashboard/ slack widget

### ISSUE THREAD

**Issue by bp85** [shlomizadok/foreman_slack#2]
Hi, 
We are getting this error lately in foreman dashboard , don't know what caused the issue
<img width="387" alt="foreman_slack" src="https://cloud.githubusercontent.com/assets/17888860/26684864/69f8731c-46b6-11e7-9ed2-fa8fb4746a25.png">

we are using foreman 1.13.0 version

**Comment by shlomizadok** [comment]
Hey,
The cause for this issue is this line:
https://github.com/shlomizadok/foreman_slack/blob/master/lib/foreman_slack/engine.rb#L31

(which I have no clue why I have added it).
You can remove it as a quick solution until I'll release a new version (this weekend hopefully)

Thanks!

**Comment by bp85** [comment]
Thanks for your quick response,
That resolved the issue

**Comment by shlomizadok** [comment]
Pushed a new version (0.0.3) to https://rubygems.org/gems/foreman_slack
Thanks for reporting!
